### PR TITLE
Changed dhcpd.conf File dependency to Concat.

### PR DESCRIPTION
**Pull request by chrisdaish**
dhcpd.conf file should be of type Concat rather than File.

### CODE REVIEW

**Comment by evidex** [comment]
+1 Leaving this dependency as File breaks the install on Ubuntu 14.04.

**Comment by stepanstipl** [comment]
+1 Does not work on RHEL7

**Comment by tphoney** [comment]
Hi @chrisdaish, thanks for the work you have put in to this pull request. However due to inactivity and the concerns raised by the other contributors this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Comment by tphoney** [comment]
Ignore my ignorance.

**Comment by chrisdaish** [comment]
Awesome, any chance of an official release on the forge anytime soon? Noticed its not been updated since Jul 2014.

**Comment by tphoney** [comment]
I have put it on the list. Thanks for the work !

**Pull request merged**
